apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        configmap-checksum: "v2"
    spec:
      containers:
        - name: frontend
          image: 827812789584.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:20250724031230
          ports:
            - containerPort: 3001
          env:
            - name: GREETING_TEXT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: greeting
            - name: BACKEND_URL
              value: https://backend.client88.me
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10

